WIP: Try to get playground to work in Xcode 12.
Xcode 12 can import switch packages directly into Playgrounds, so I removed the Xcode project and workspace and just added a playground. The import works fine, but it currently gives the following error message:

```text
error: Couldn't lookup symbols:
  Playground_Sources.showParserView<A where A: Patterns.Pattern, A.Input == Swift.String>(ofSize: __C.CGSize, pattern: A, withText: Swift.String) throws -> ()
  Playground_Sources.showParserView<A where A: Patterns.Pattern, A.Input == Swift.String>(ofSize: __C.CGSize, pattern: A, withText: Swift.String) throws -> ()
```

and so on.

Had to move all the playgrounds internal source code into one file because it couldn't find structs across files.