Fix travis build (#11)
* Travis: run unit tests in release build. To avoid timeout.

Also just build Xcode project, don't run unit tests. They have already been run using the Swift package manager.

* Travis: don't import @testable on Linux.

fixes error: module 'PerformanceTests' was not compiled for testing

* Travis: try automatic test discovery on Linux.

* Travis: test in debug mode on Linux, release mode on macOS. Use Xcode 11 image.

Tries to solve https://travis-ci.org/NotTooBadSoftware/textpicker/jobs/571933560:

home/travis/build/NotTooBadSoftware/textpicker/.build/x86_64-unknown-linux/release/testlist.derived/PatternsTests.swift:2:18: error: module 'PatternsTests' was not compiled for testing
461@testable import PatternsTests
462                 ^
463
464The command "swift test -c release --enable-index-store --enable-test-discovery" exited with 1.
465
466

* Travis: fix indentation of Travis file.

"Could not parse NotTooBadSoftware/textpicker/.travis.yml@b8926b84250700a1"

* Remove Linux specific unit testing stuff, no longer needed.

Because now Swift for Linux can discover unit tests all by itself.

* Put back LinuxMain.swift because Swift for Linux says so.

https://travis-ci.org/NotTooBadSoftware/textpicker/jobs/572432124#L455

error: missing LinuxMain.swift file in the Tests directory
456
The command "swift build" exited with 1.
457
458