Put back LinuxMain.swift because Swift for Linux says so.
https://travis-ci.org/NotTooBadSoftware/textpicker/jobs/572432124#L455

error: missing LinuxMain.swift file in the Tests directory
456
The command "swift build" exited with 1.
457
458